import numpy as np
import matplotlib.pyplot as plt
rng = np.random.default_rng(576)
fig, ax = plt.subplots(2, 2, figsize=(9, 7))
t = np.linspace(0, 4 * np.pi, 400)
ax[0, 0].plot(t, np.exp(-0.2 * t) * np.sin(2 * t), label=r'$e^{-0.2t}\sin 2t$')
ax[0, 0].plot(t, np.exp(-0.2 * t), 'k--', lw=1, label='envelope')
ax[0, 0].plot(t, -np.exp(-0.2 * t), 'k--', lw=1)
ax[0, 0].set_title('Damped oscillation')
ax[0, 0].legend()
pts = rng.multivariate_normal([0, 0], [[1, 0.8], [0.8, 1]], 500)
sc = ax[0, 1].scatter(pts[:, 0], pts[:, 1], c=np.arctan2(pts[:, 1], pts[:, 0]), cmap='twilight', s=12)
ax[0, 1].set_title('Correlated Gaussian (rho = 0.8)')
ax[0, 1].set_aspect('equal')
fig.colorbar(sc, ax=ax[0, 1], label='angle')
z = rng.standard_normal(2000)
ax[1, 0].hist(z, bins=40, density=True, alpha=0.6, label='samples')
xs = np.linspace(-4, 4, 200)
ax[1, 0].plot(xs, np.exp(-xs**2 / 2) / np.sqrt(2 * np.pi), 'r', label='N(0,1) pdf')
ax[1, 0].set_title('Histogram vs. density')
ax[1, 0].legend()
X, Y = np.meshgrid(np.linspace(-3, 3, 200), np.linspace(-3, 3, 200))
Zg = np.sin(X) * np.cos(Y)
im = ax[1, 1].imshow(Zg, extent=[-3, 3, -3, 3], origin='lower', cmap='RdBu_r')
ax[1, 1].contour(X, Y, Zg, levels=8, colors='k', linewidths=0.5)
ax[1, 1].set_title(r'$\sin x \cos y$')
fig.colorbar(im, ax=ax[1, 1])
fig.suptitle('ELEC 576 Assignment 0, Task 4: a Matplotlib figure of my choice')
fig.tight_layout()
plt.show()
fig.savefig('task4_figure.png', dpi=150, bbox_inches='tight')
